services:
  postgres:
    container_name: postgres-db
    image: postgres:14
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: microservice
      POSTGRES_PASSWORD: example123

  app:
    depends_on:
    - postgres
    build:
      context: .
    container_name: microserver
    image: microservice-demo
    ports:
    - 8080:80
    environment:
      PGHOST: postgres-db
      PGDB: microservice
      PGUSER: microservice
      PGPASSWORD: example123
