apiVersion: v1
kind: Pod
metadata:
  name: users
  labels:
    app: users
spec:
  containers:
    - name: users
      image: bruc3mackenzi3/users:1.0
      ports:
        - containerPort: 8080
          name: users-http
      env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: microservice
        - name: POSTGRES_USER
          value: microservice
        - name: POSTGRES_PASSWORD
          value: example123
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: NodePort
  selector:
    app: users
  ports:
    - name: http
      port: 8080
      nodePort: 30080
      targetPort: users-http
